from pathlib import Path
import json
base=Path('rhine_exact/output/dock-phone-fix-20260914')
p=base/'verification.json';old=json.loads(p.read_text(encoding='utf8'));(base/'verification-all-pages-superseded.json').write_text(json.dumps(old,ensure_ascii=False,indent=2),encoding='utf8')
current={'date':'2026-09-14','device_serial':'16c18d67','launcher':'com.miui.home','requirement':'Dock visible only on actual HyperOS page 2','status':'incomplete; phone interaction paused after foreground changed to another application','phone_change':{'homepg':'2','horizontal_screen_count':4,'native_scroll_secure_setting':'1 (original value; refreshed 0 then 1)'},'saved_on_phone':True,'verification':{'initial_actual_page2':'Dock visible briefly after editor save','repeat_actual_page1':'Dock hidden','repeat_actual_page2':'Dock hidden unexpectedly','repeat_actual_page3':'Dock hidden','repeat_actual_page4':'Dock hidden'},'evidence':'second-page-only/verified-page[1-4].png and .xml; earlier page3.png actually depicts native page2 and page2.png depicts native page1','next':'Add temporary live screen/homepg/page diagnostic via native editor, compare actual four pages, then remove diagnostic. Editor preview screen number alone is not conclusive.','not_done':['No permanent native page bridge','No APK modification','No new app installed']}
p.write_text(json.dumps(current,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(base/'修复记录.md').write_text('# 侧边工具条第二页显示排查\n\n当前要求：只在澎湃真实第 2 页显示。\n\n已保存 homepg=2，横向页数设置为 4；原生壁纸滚动设置保持原值 1，并触发过刷新。\n\n结果尚未通过：保存后第 2 页曾显示工具条，但重新逐页检查时第 2 页也隐藏。真实页码由桌面无障碍节点确认，四页截图及 XML 保存在 second-page-only/verified-page*。\n\n旧的全页显示方案已撤回。旧记录仅保存在 verification-all-pages-superseded.json。下一步需要在实际桌面显示临时实时页码，核对系统翻页回调和主题条件；验证后移除诊断组件。手机切入其他应用后暂停触控，等待用户重新交接。\n',encoding='utf8')
p=Path('rhine_exact/output/free-editor-rebuild/sync-status.json');d=json.loads(p.read_text(encoding='utf8'));d['current_phone_compatibility']={'global':'homepg','after':'2','horizontal_screen_count':4,'requirement':'only actual HyperOS page 2','verification':'incomplete; page2 Dock disappeared during repeat test'};p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Current requirement and incomplete verification recorded.')
